### ISSUE TITLE
Why not bother use strlen()?

### ISSUE THREAD

**Issue by Explorer09** [MrKrzYch00/zopfli#13]
This is more of a question than a bug report.
In several places in the code, I see several loop patterns like this:
```
for(k=i;initdir[k]!='\0';k++) {}
```
and this:
```
for(i = 0;infilename[i]!='\0';i++) {}
```
which are equivalent to strlen() calls (though I argue the latter would be more readable).
May I ask, was there any reason to avoid the strlen function call? (If you wish, I can file a pull request to convert all of such loops to strlen.)

**Comment by MrKrzYch00** [comment]
Don't worry, I know what strlen is, I use it with PHP a lot. The reason, I think, was to evade the need to include string.h long time ago where it would be needed just for that in some places. Not sure how it relates to current code stage. For me both ways are pretty readable. Though I would like it to stay the way it is, unless it's done in heavy work places and you can prove it has impact on performance.

**Comment by Explorer09** [comment]
If I have time, I would really like to test the performance between strlen() and the naive loop approach.

For me, I would consider strlen() always better as compiler can recognize it and turn it to constant whenever it make sense, and strlen() in libc is tuned for performance ([it checks by word instead of by byte](https://stackoverflow.com/questions/34642994/understanding-code-in-strlen-implementation)). But again the performance should be tested instead of assumed.

**Comment by MrKrzYch00** [comment]
AFAIK those optimizations are not deterministic. They vary from platform to platform. On RISC systems certain built-in function may perform better than it does on CISC ones and vice-versa.

**Comment by MrKrzYch00** [comment]
WONTFIX. This is not really a problem for it to stay like it is.
