### ISSUE TITLE
Issues linking on Linux

### ISSUE THREAD

**Issue by Faalagorn** [MrKrzYch00/zopfli#20]
I tried to build the program on Linux, but it failed during linking process. Turned The fix for me was to remove this line https://github.com/MrKrzYch00/zopfli/blob/f33ef67d68aa60a2c340f4c9cbfa1031f358e643/src/zopfli/inthandler.c#L6 as linker said that the variable is defined twice (second one being here I guess): https://github.com/MrKrzYch00/zopfli/blob/f33ef67d68aa60a2c340f4c9cbfa1031f358e643/src/zopfli/inthandler.h#L4

I can make a PR to remove the line that help me get the program runinng, but I'm not sure if it's a proper way, especially as I didn't troubleshoot it too much or tried compiling with different programs/computers/options (though I did have trouble when I tried compiling with `-fprofile-generate` I didn't troubleshoot further).

Something to be looked into I guess, wonder if anyone else had this issue, as I assume others got it running after all – might be GNU linker on Linux being more picky than others. :)

**Comment by MrKrzYch00** [comment]
Yes, I can confirm the problem with linking it using newer GCC in MSYS2. The reason for this variable was to hold the CTRL+C trigger for zopfli when pressed during zopfliPNG optimization stage AFAIK. It was never completely supported for zopfliPNG, because it should speed-up filtering as well.

Temporarily fix is to comment out the line in inthandler.c, but CTRL+C will no longer work properly when pressed before zopfli final compression stage.

CTRL+C feature is also known to not close the software when pressed twice on linux, where it does on windows, and was done for zopfli in mind, not zopfliPNG.

**Comment by Faalagorn** [comment]
Thanks! I'll try the workaround for my build locally. Do you plan for a proper fix soon-ish or maybe the workaround could be applied to the install script to be passed as argument for those affected?

**Comment by MrKrzYch00** [comment]
Best would be to control everything through some control thread with keyboard inputs and remove interrupt handlers altogether. Though it requires correct communication along the way: control thread -> master -> working threads, and zopflipng would require to be threaded as well and have additional controls that would also be passed later as initial setup to zopfli (overriding previously passed command line switches). The information on screen would also need to be readable and not overlap for this…

Idea I had before…

Though there are much more important issues to look at, than this…

**Comment by MrKrzYch00** [comment]
Fixed with latest commit. Note that CTRL+C may not work properly during ZopfliPNG stage and have no impact on Zopfli, unless pressed during Zopfli stage, so at the moment there is a regression in that functionality.

**Comment by Faalagorn** [comment]
I tested it and at the first glance ctrl+c **do** seem to work for me, so guess I'm gonna close the issue for now.

I'll be doing more tests though, so in case I spot something I'll let you know – feel free to reopen the issue if needed, too!
